FEAT : add validator
Injury-law-assist/backend pull request #3
Opened 2024-07-06 14:51 UTC by KyeongYeongDEV

2024-07-06 14:52 UTC, KNU-K commented
@KyeongYeongDEV base메인으로 박지마셈

2024-07-06 14:55 UTC, KyeongYeongDEV commented
아 맞다 오키오키

2024-07-06 14:57 UTC, KNU-K requested changes

2024-07-06 14:57 UTC, KNU-K commented on src/api/middlewares/validator.middleware.ts
> +const serValidator =  async(req : Request, res : Response, next : NextFunction)=>{
`serValidator` 함수 이름이 정확히 의미하는 바가 뭐지?

2024-07-06 14:57 UTC, KNU-K commented on src/api/middlewares/validator.middleware.ts
> +    }catch(error){
에러 처리는 제거해줘 후반에 할거야

2024-07-06 14:57 UTC, KNU-K commented on src/schemas/joinRoom.schema.ts
> +export const JoinRoomSchema =Joi.object({
```sql
create database exam_iia;
-- Use database
USE exam_iia;

-- User table
CREATE TABLE IF NOT EXISTS users (
    u_id INT AUTO_INCREMENT PRIMARY KEY,
    u_email VARCHAR(255) NOT NULL,
    u_password VARCHAR(255) NOT NULL,
    u_nickname VARCHAR(255),
    u_created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    u_updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- ChatRoom table
CREATE TABLE IF NOT EXISTS chatRooms (
    cr_id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) not null,
    u_id INT,
    cr_created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    cr_updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY (u_id) REFERENCES users(u_id)
);


-- Message table
CREATE TABLE IF NOT EXISTS messages (
    m_id INT AUTO_INCREMENT PRIMARY KEY,
    cr_id INT,
    u_id INT,
    m_content TEXT,
    m_created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    m_updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (cr_id) REFERENCES chatRooms(cr_id),
    FOREIGN KEY (u_id) REFERENCES users(u_id)
);

```
db 구조 바꼈어. join 은 없어졌어 참고해줘

2024-07-06 14:57 UTC, KNU-K commented on src/schemas/message.schema.ts
> +	m_created_at: Joi.date()
음 내가 말하거랑 뉘앙스가 다르네, 나는 end-point 에서 필요한거 말한거야.
예시를 들면, post 할 때 body 에 무슨 요소 필요한가?
get 할때 parameter에 무슨 요소가 필요한가? 야
수정해줘

2024-07-06 14:59 UTC, KNU-K commented on src/schemas/message.schema.ts
> +	m_created_at: Joi.date()
+ end-point 기준으로 하면 created_at 이나 updated_at 은 직접 받는 값이 아니니깐 필요없겠지?

+ 그리고 저거 이외의 내용 추가 안되게 할 수 있을거야 찾아보고 해줘

2024-07-06 15:01 UTC, KyeongYeongDEV commented on src/api/middlewares/validator.middleware.ts
> +const serValidator =  async(req : Request, res : Response, next : NextFunction)=>{
userValidator 오타 .. 죄송..

2024-07-06 16:57 UTC, KyeongYeongDEV commented on src/schemas/message.schema.ts
> +	m_created_at: Joi.date()
AUTO_INCREMENT 되는 값도 넣을 필요 없나?

2024-07-06 17:00 UTC, KNU-K commented on src/schemas/message.schema.ts
> +	m_created_at: Joi.date()
@KyeongYeongDEV 어어 없으. 그냥 내 router 지금 보고 들어올만한거 확인하센 
#2  이쪽 눌러봐

2024-07-07 08:36 UTC, KNU-K requested changes

2024-07-07 08:36 UTC, KNU-K commented on src/schemas/chat.schema.ts
> +
여기 느낌 좋다. 이런느낌으로 살려서 ㄱㄱ

2024-07-07 08:36 UTC, KNU-K commented on src/schemas/user.schema.ts
> +    password : Joi.string()
정규식쪽은 주석으로 처리해둬. 프론트에서 처리하기 힘드니깐, 테스트 완료되면 넣자.

2024-07-07 08:36 UTC, KNU-K commented on src/schemas/user.schema.ts
> +    password : Joi.string()
email은 놔두고

2024-07-07 11:26 UTC, KNU-K approved these changes
👍

2024-07-07 11:26 UTC, merged